version: '3.8'
services:
  # jaeger:
  #  image: jaegertracing/all-in-one:1.49
  # redis:
  #  image: redis:7.0
  rabbitmq:
   image: rabbitmq:3.12.2-management
  otel-collector:
   image: otel/opentelemetry-collector-contrib:0.85.0
  metric.api:
   image: metric.api:image
   build:
    context: .
    dockerfile: Observability.MetricAPI/Dockerfile
  prometheus:
   image: prom/prometheus:latest
   volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
  # elasticsearch:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.7.1
   